name: graphql_schema2
version: 3.0.0
description: An implementation of GraphQL's type system in Dart. Basis of graphql_server2.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/graphql_dart/tree/master/graphql_schema
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.4.0
  source_span: ^1.8.1
dev_dependencies:
  test: ^1.20.0
  lints: ^1.0.0
