name: graphql_server2
version: 2.1.1
description: Base package for implementing GraphQL servers. You might prefer `package:angel3_graphql`, the fastest way to implement GraphQL backends in Dart.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/graphql_dart/tree/master/graphql_server

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  angel3_serialize: ^4.0.0
  graphql_schema2: ^2.1.0
  graphql_parser2: ^2.1.0
  collection: ^1.15.0
  meta: ^1.4.0
  recase: ^4.0.0
  stream_channel: ^2.1.0
  tuple: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.5

dependency_overrides:
  graphql_parser2:
    path: ../graphql_parser
  graphql_schema2:
    path: ../graphql_schema
