name: graphql_generator
version: 2.0.0
description: Generates GraphQL schemas from Dart classes, for use with pkg:graphql_server.
homepage: https://github.com/angel-dart/graphql
publish_to: none
environment:
  sdk: ">=2.10.0 <3.0.0"
dependencies:
  analyzer: ">=0.27.1 <2.0.0"
  angel_model: #^1.0.0
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/model
  angel_serialize_generator:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/serialize/angel_serialize_generator
  graphql_schema:
    git: 
      url: https://github.com/dukefirehawk/angel.git
      ref: sdk-2.12.x_nnbd
      path: packages/graphql/graphql_schema
  build: ^1.0.0
  build_config: ^0.3.0
  code_builder: ^3.0.0
  recase: ^2.0.0
  source_gen: ^0.9.4
dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.0.0