name: graphql_parser2
version: 3.0.0
description: Parses GraphQL queries and schemas. Also includes classes for the GraphQL AST.
homepage: https://angel3-framework.web.app/
repository: https://github.com/dukefirehawk/graphql_dart/tree/master/graphql_parser
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  charcode: ^1.3.1
  source_span: ^1.8.1
  string_scanner: ^1.1.0
dev_dependencies:
  matcher: ^0.12.10
  lints: ^1.0.0
  test: ^1.20.0
